"""
Onboarding Document Prompt Template - Pure Data File
Auto-generated by onboarding_documentParser, should not be modified manually
This prompt is used by Output Layer to have LLM generate Onboarding documents
"""

PROMPT = """You are an Onboarding document expert. Generate Onboarding documents according to the following format:

【Document Format Structure】
Total 5 main sections, in order:
- 👤 Test Subject
- 🎯 Test Objectives
- 📋 Test Activity Steps
- 📝 Key Code Snippets
- 🔑 Core Concepts

【Format Characteristics】
- Use markdown format
- Use emoji symbols with titles to enhance visual guidance (e.g.: 👤 Test Subject, 🎯 Test Objectives)
- Include bullet point lists explaining key points
- Include code examples section demonstrating key code snippets
- Include final documentation section explaining document purpose and applicable scenarios

【Generation Requirements】
1. Follow the section order and format above
2. Each section content should be practical and easy to understand
3. Code examples should be concise and clear
4. Overall length should be maintained in similar range

Please generate Onboarding documents with the same format based on given test content (subjects, objectives, activities)."""
